package com.mobileweb.model;

// Generated Apr 17, 2014 12:02:10 AM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Calendar;
import java.util.Date;
import java.util.Map;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * User generated by hbm2java
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Entity
@Table(name = "USER", catalog = "MobileWeb")
public class User implements java.io.Serializable {

	private Integer userId;
	private String firstName;
	private String lastName;
	private String username;
	private String email;
	private String homeAddress;
	private Integer phoneNumber;
	private String password;
	private String ecLastName;
	private String ecFirstName;
	private Integer ecPhoneNumber;
	private Date createdAt;
	private Date updatedAt;

	public User() {
	}

	public User(String firstName, String lastName, String username, String password, Date createdAt, Date updatedAt) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.username = username;
		this.password = password;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public User(Map<String, String[]> data) {
		this.username = getDataNotNull("userName", data, "");
		this.firstName = getDataNotNull("firstName", data, "");
		this.lastName = getDataNotNull("lastName", data, "");
		this.email = getDataNotNull("email", data, "");
		this.password = getDataNotNull("password", data, "");
		this.homeAddress = getDataNotNull("homeAddress", data, "");
		this.phoneNumber = Integer.parseInt(getDataNotNull("phoneNumber", data, "0"));
		this.ecFirstName = getDataNotNull("ecFirstName", data, "");
		this.ecLastName = getDataNotNull("ecLastName", data, "");
		this.ecPhoneNumber = Integer.parseInt(getDataNotNull("ecPhoneNumber", data, "0"));
		this.createdAt = Calendar.getInstance().getTime();
		this.updatedAt = Calendar.getInstance().getTime();
	}

	private String getDataNotNull(String key, Map<String, String[]> data, String defaut) {
		String ret = defaut;
		try {
			ret = data.get(key)[0];
		} catch (Exception e) {
			ret = defaut;
			e.printStackTrace();
		}
		return ret;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "userId", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "firstName")
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "userName")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdAt", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedAt", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "email")
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "homeAddress")
	public String getHomeAddress() {
		return homeAddress;
	}

	public void setHomeAddress(String homeAddress) {
		this.homeAddress = homeAddress;
	}

	@Column(name = "phoneNumber")
	public Integer getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(Integer phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "ecLastName")
	public String getEcLastName() {
		return ecLastName;
	}

	public void setEcLastName(String ecLastName) {
		this.ecLastName = ecLastName;
	}

	@Column(name = "ecFirstName")
	public String getEcFirstName() {
		return ecFirstName;
	}

	public void setEcFirstName(String ecFirstName) {
		this.ecFirstName = ecFirstName;
	}

	@Column(name = "ecPhoneNumber")
	public Integer getEcPhoneNumber() {
		return ecPhoneNumber;
	}

	public void setEcPhoneNumber(Integer ecPhoneNumber) {
		this.ecPhoneNumber = ecPhoneNumber;
	}

}
